source "https://rubygems.org"

gem "sinatra",         "~> 1.4.2"
gem "redcarpet",       "~> 2.2.2"
gem "pygments.rb",     "~> 0.5.0"
gem "rake",            "~> 10.0.4"
gem "sass",            "~> 3.2.9"
gem "coffee-script",   "~> 2.2.0"
gem "slim",            "~> 1.3.8"
gem "shotgun",         "~> 0.9"
